### ISSUE TITLE
Toast Notification Example Doesn't Work on Windows 10

### ISSUE THREAD

**Issue by Eilie** [contextfree/winrt-rust#44] opened 2017-10-30 13:14 UTC
Hello,

After cloning the repo and executing
```
cargo run --example toast_notify --features "windows-data windows-ui"
```
Nothing really happens, no error, no toast, nothing. Program exits with code 0.
Not sure how to debug it. I could give more info but not sure what matters as well.
My rustc version is 1.23-nightly.
https://github.com/allenbenz/winrt-notification Doesn't work as well in same way.

**Comment by Boddlnagg** [comment] 2017-10-30 17:12
I can reproduce this problem here ... the culprit seems to be the Fall Creators Update. See this [stackoverflow answer](https://stackoverflow.com/a/46817674).

Replacing the AppId `"myrustapp.exe"` with `"{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WindowsPowerShell\\v1.0\\powershell.exe"` in the example code in `toast_notify.rs` "fixes" this issue for me (in the sense that the notification appears again, but it is displayed as belonging to PowerShell).

I don't know if I should commit that kind of workaround, but anything else (like registering your own AppId) is probably out of scope for such a simple example.

By the way, Microsoft's API documentation has always stated that you need your own AppId for this to work, and it was actually a "bug" before Fall Creators Update that it worked with a bogus AppId such as `"myrustapp.exe"`.

**Comment by Boddlnagg** [comment] 2017-10-31 10:12
It works on master now. I just used PowerShell's App ID, which is not very pretty, but this is just an example anyway ...

**Closed as completed** 2017-10-31 10:11 UTC
